use super::{
    AobToken, HookProfile, HookSignature, HookTarget, MonitorIdentityOffsets, SignatureLocator,
    SwapChainVtablePath,
};
use AobToken::{Exact, Wildcard};

const PRESENT_AOB: &[AobToken] = &[
    Exact(0x40),
    Exact(0x55),
    Exact(0x53),
    Exact(0x56),
    Exact(0x57),
    Exact(0x41),
    Exact(0x54),
    Exact(0x41),
    Exact(0x55),
    Exact(0x41),
    Exact(0x56),
    Exact(0x41),
    Exact(0x57),
    Exact(0x48),
    Exact(0x8D),
    Exact(0x6C),
    Exact(0x24),
    Exact(0xF9),
    Exact(0x48),
    Exact(0x81),
    Exact(0xEC),
    Exact(0xF8),
    Exact(0x00),
    Exact(0x00),
    Exact(0x00),
    Exact(0x48),
    Exact(0x8B),
    Exact(0x05),
    Wildcard,
    Wildcard,
    Wildcard,
    Wildcard,
    Exact(0x48),
    Exact(0x33),
    Exact(0xC4),
    Exact(0x48),
    Exact(0x89),
    Exact(0x45),
    Exact(0xEF),
    Exact(0x4C),
    Exact(0x8B),
    Exact(0x65),
    Wildcard,
    Exact(0x48),
    Exact(0x8B),
    Exact(0xD9),
];

const IS_CANDIDATE_DIRECT_FLIP_COMPATIBLE_AOB: &[AobToken] = &[
    Exact(0x48),
    Exact(0x8B),
    Exact(0xC4),
    Exact(0x48),
    Exact(0x89),
    Exact(0x58),
    Exact(0x08),
    Exact(0x48),
    Exact(0x89),
    Exact(0x68),
    Exact(0x10),
    Exact(0x48),
    Exact(0x89),
    Exact(0x70),
    Exact(0x18),
    Exact(0x48),
    Exact(0x89),
    Exact(0x78),
    Exact(0x20),
    Exact(0x41),
    Exact(0x56),
    Exact(0x48),
    Exact(0x83),
    Exact(0xEC),
    Exact(0x20),
    Exact(0x33),
    Exact(0xDB),
    Exact(0x4D),
    Exact(0x8B),
    Exact(0xF1),
];

const OVERLAYS_ENABLED_AOB: &[AobToken] = &[
    Exact(0x83),
    Exact(0x3D),
    Wildcard,
    Wildcard,
    Wildcard,
    Wildcard,
    Exact(0x05),
    Exact(0x74),
    Exact(0x09),
    Exact(0x83),
    Exact(0x79),
    Exact(0x28),
    Exact(0x01),
    Exact(0x0F),
    Exact(0x97),
    Exact(0xC0),
    Exact(0xC3),
    Exact(0xCC),
    Exact(0x32),
    Exact(0xC0),
    Exact(0xC3),
];

const DISABLE_INDEPENDENT_FLIP_ANCHOR_AOB: &[AobToken] = &[
    Exact(0x83),
    Exact(0x3D),
    Wildcard,
    Wildcard,
    Wildcard,
    Wildcard,
    Exact(0x00),
    Exact(0x75),
    Exact(0x18),
    Exact(0x48),
    Exact(0x8B),
    Exact(0x96),
    Exact(0x88),
    Exact(0x31),
    Exact(0x00),
    Exact(0x00),
    Exact(0x44),
    Exact(0x0F),
    Exact(0xB6),
    Exact(0xC3),
    Exact(0x49),
    Exact(0x03),
    Exact(0xD6),
    Exact(0x48),
    Exact(0x8B),
    Exact(0xCE),
];

const DIRECT_FLIP_INFO_ENSURE_INDEPENDENT_FLIP_AOB: &[AobToken] = &[
    Exact(0x48),
    Exact(0x89),
    Exact(0x5C),
    Exact(0x24),
    Exact(0x08),
    Exact(0x48),
    Exact(0x89),
    Exact(0x6C),
    Exact(0x24),
    Exact(0x10),
    Exact(0x48),
    Exact(0x89),
    Exact(0x74),
    Exact(0x24),
    Exact(0x18),
    Exact(0x57),
    Exact(0x48),
    Exact(0x83),
    Exact(0xEC),
    Exact(0x30),
    Exact(0x33),
    Exact(0xDB),
    Exact(0x48),
    Exact(0x8B),
    Exact(0xF9),
    Exact(0x38),
    Exact(0x59),
    Exact(0x6A),
];

const IS_DIRECT_FLIP_SUPPORTED_ON_TARGET_AOB: &[AobToken] = &[
    Exact(0x48),
    Exact(0x89),
    Exact(0x5C),
    Exact(0x24),
    Exact(0x20),
    Exact(0x55),
    Exact(0x56),
    Exact(0x57),
    Exact(0x48),
    Exact(0x83),
    Exact(0xEC),
    Exact(0x60),
    Exact(0x48),
    Exact(0x8B),
    Exact(0x05),
    Wildcard,
    Wildcard,
    Wildcard,
    Wildcard,
    Exact(0x48),
    Exact(0x33),
    Exact(0xC4),
];

const LEGACY_SWAP_CHAIN_CHECK_DIRECT_FLIP_AOB: &[AobToken] = &[
    Exact(0x40),
    Exact(0x55),
    Exact(0x53),
    Exact(0x56),
    Exact(0x57),
    Exact(0x41),
    Exact(0x54),
    Exact(0x41),
    Exact(0x55),
    Exact(0x41),
    Exact(0x56),
    Exact(0x41),
    Exact(0x57),
    Exact(0x48),
    Exact(0x8D),
    Exact(0xAC),
    Exact(0x24),
    Exact(0xE8),
    Exact(0xFE),
    Exact(0xFF),
    Exact(0xFF),
    Exact(0x48),
    Exact(0x81),
    Exact(0xEC),
    Exact(0x18),
    Exact(0x02),
    Exact(0x00),
    Exact(0x00),
    Exact(0x48),
    Exact(0x8B),
    Exact(0x05),
    Wildcard,
    Wildcard,
    Wildcard,
    Wildcard,
    Exact(0x48),
    Exact(0x33),
    Exact(0xC4),
    Exact(0x48),
    Exact(0x89),
    Exact(0x85),
    Exact(0x00),
    Exact(0x01),
    Exact(0x00),
    Exact(0x00),
    Exact(0xF3),
    Exact(0x0F),
    Exact(0x10),
];

const IS_ADVANCED_DIRECT_FLIP_COMPATIBLE_AOB: &[AobToken] = &[
    Exact(0x40),
    Exact(0x53),
    Exact(0x48),
    Exact(0x83),
    Exact(0xEC),
    Exact(0x20),
    Exact(0x48),
    Exact(0x8B),
    Exact(0x89),
    Wildcard,
    Wildcard,
    Wildcard,
    Wildcard,
    Exact(0x48),
    Exact(0x85),
    Exact(0xC9),
    Exact(0x74),
    Wildcard,
    Exact(0x48),
    Exact(0x83),
    Exact(0x64),
    Exact(0x24),
    Exact(0x30),
    Exact(0x00),
];

const SIGNATURES: &[HookSignature] = &[
    HookSignature {
        target: HookTarget::Present,
        locator: SignatureLocator::Aob {
            tokens: PRESENT_AOB,
        },
    },
    HookSignature {
        target: HookTarget::IsCandidateDirectFlipCompatible,
        locator: SignatureLocator::Aob {
            tokens: IS_CANDIDATE_DIRECT_FLIP_COMPATIBLE_AOB,
        },
    },
    HookSignature {
        target: HookTarget::DirectFlipInfoEnsureIndependentFlipState,
        locator: SignatureLocator::Aob {
            tokens: DIRECT_FLIP_INFO_ENSURE_INDEPENDENT_FLIP_AOB,
        },
    },
    HookSignature {
        target: HookTarget::IsDirectFlipSupportedOnTarget,
        locator: SignatureLocator::Aob {
            tokens: IS_DIRECT_FLIP_SUPPORTED_ON_TARGET_AOB,
        },
    },
    HookSignature {
        target: HookTarget::LegacySwapChainCheckDirectFlipSupport,
        locator: SignatureLocator::Aob {
            tokens: LEGACY_SWAP_CHAIN_CHECK_DIRECT_FLIP_AOB,
        },
    },
    HookSignature {
        target: HookTarget::IsAdvancedDirectFlipCompatible,
        locator: SignatureLocator::Aob {
            tokens: IS_ADVANCED_DIRECT_FLIP_COMPATIBLE_AOB,
        },
    },
    HookSignature {
        target: HookTarget::OverlayTestMode,
        locator: SignatureLocator::RipRelativeGlobalAob {
            tokens: OVERLAYS_ENABLED_AOB,
            displacement_offset: 2,
            instruction_size: 7,
        },
    },
    HookSignature {
        target: HookTarget::DisableIndependentFlip,
        locator: SignatureLocator::RipRelativeGlobalAob {
            tokens: DISABLE_INDEPENDENT_FLIP_ANCHOR_AOB,
            displacement_offset: 2,
            instruction_size: 7,
        },
    },
    HookSignature {
        target: HookTarget::OverlaysEnabled,
        locator: SignatureLocator::Aob {
            tokens: OVERLAYS_ENABLED_AOB,
        },
    },
];

pub(super) fn profile() -> HookProfile {
    HookProfile {
        signatures: SIGNATURES,
        swap_chain: SwapChainVtablePath {
            container_vtable_index: 24,
            resource_vtable_index: 19,
        },
        hardware_protected_offset: 0x64,
        monitor_identity: MonitorIdentityOffsets {
            adapter_luid_low_offset: 0x34,
            adapter_luid_high_offset: 0x38,
            target_id_offset: 0x3c,
        },
    }
}
