use super::{
    AobToken, ClipBoxPathHypothesis, HardwareProtectedPathHypothesis, HookProfile, HookSignature,
    HookTarget, MonitorIdentityPathHypothesis, ProfileHypotheses, SignatureLocator,
    SwapChainPathHypothesis,
};
use AobToken::{Exact, Wildcard};

const PRESENT_AOB: &[AobToken] = &[
    Exact(0x40),
    Exact(0x55),
    Exact(0x53),
    Exact(0x56),
    Exact(0x57),
    Exact(0x41),
    Exact(0x54),
    Exact(0x41),
    Exact(0x55),
    Exact(0x41),
    Exact(0x56),
    Exact(0x41),
    Exact(0x57),
    Exact(0x48),
    Exact(0x8D),
    Exact(0x6C),
    Exact(0x24),
    Exact(0xF9),
    Exact(0x48),
    Exact(0x81),
    Exact(0xEC),
    Exact(0xF8),
    Exact(0x00),
    Exact(0x00),
    Exact(0x00),
    Exact(0x48),
    Exact(0x8B),
    Exact(0x05),
    Wildcard,
    Wildcard,
    Wildcard,
    Wildcard,
    Exact(0x48),
    Exact(0x33),
    Exact(0xC4),
    Exact(0x48),
    Exact(0x89),
    Exact(0x45),
    Exact(0xEF),
    Exact(0x4C),
    Exact(0x8B),
    Exact(0x65),
    Wildcard,
    Exact(0x48),
    Exact(0x8B),
    Exact(0xD9),
];

const OVERLAY_DIRECT_FLIP_AOB: &[AobToken] = &[
    Exact(0x48),
    Exact(0x8B),
    Exact(0xC4),
    Exact(0x48),
    Exact(0x89),
    Exact(0x58),
    Exact(0x08),
    Exact(0x48),
    Exact(0x89),
    Exact(0x68),
    Exact(0x10),
    Exact(0x48),
    Exact(0x89),
    Exact(0x70),
    Exact(0x18),
    Exact(0x48),
    Exact(0x89),
    Exact(0x78),
    Exact(0x20),
    Exact(0x41),
    Exact(0x56),
    Exact(0x48),
    Exact(0x83),
    Exact(0xEC),
    Exact(0x20),
    Exact(0x33),
    Exact(0xDB),
    Exact(0x4D),
    Exact(0x8B),
    Exact(0xF1),
];

const OVERLAY_TEST_MODE_ANCHOR_AOB: &[AobToken] = &[
    Exact(0x83),
    Exact(0x3D),
    Wildcard,
    Wildcard,
    Wildcard,
    Wildcard,
    Exact(0x05),
    Exact(0x74),
    Exact(0x09),
    Exact(0x83),
    Exact(0x79),
    Exact(0x28),
    Exact(0x01),
    Exact(0x0F),
    Exact(0x97),
    Exact(0xC0),
    Exact(0xC3),
];

const WINDOW_CONTEXT_DIRECT_FLIP_AOB: &[AobToken] = &[
    Exact(0x48),
    Exact(0x89),
    Exact(0x5C),
    Exact(0x24),
    Exact(0x08),
    Exact(0x48),
    Exact(0x89),
    Exact(0x74),
    Exact(0x24),
    Exact(0x10),
    Exact(0x57),
    Exact(0x48),
    Exact(0x83),
    Exact(0xEC),
    Exact(0x20),
    Exact(0x41),
    Exact(0x8B),
    Exact(0xD9),
    Exact(0x48),
    Exact(0x8B),
    Exact(0xF2),
    Exact(0x4C),
    Exact(0x8B),
    Exact(0x01),
    Exact(0x48),
    Exact(0x8B),
    Exact(0xF9),
];

const COMP_SWAP_CHAIN_DIRECT_FLIP_AOB: &[AobToken] = &[
    Exact(0x48),
    Exact(0x8B),
    Exact(0xC4),
    Exact(0x48),
    Exact(0x89),
    Exact(0x58),
    Exact(0x08),
    Exact(0x48),
    Exact(0x89),
    Exact(0x68),
    Exact(0x10),
    Exact(0x48),
    Exact(0x89),
    Exact(0x70),
    Exact(0x18),
    Exact(0x48),
    Exact(0x89),
    Exact(0x78),
    Exact(0x20),
    Exact(0x41),
    Exact(0x56),
    Exact(0x48),
    Exact(0x83),
    Exact(0xEC),
    Exact(0x20),
    Exact(0x33),
    Exact(0xDB),
    Exact(0x48),
    Exact(0x8D),
    Exact(0xB9),
    Exact(0x98),
    Exact(0x01),
    Exact(0x00),
    Exact(0x00),
];

const COMP_SWAP_CHAIN_INDEPENDENT_FLIP_AOB: &[AobToken] = &[
    Exact(0x40),
    Exact(0x53),
    Exact(0x48),
    Exact(0x83),
    Exact(0xEC),
    Exact(0x40),
    Exact(0x48),
    Exact(0x8B),
    Exact(0x05),
    Wildcard,
    Wildcard,
    Wildcard,
    Wildcard,
    Exact(0x48),
    Exact(0x33),
    Exact(0xC4),
    Exact(0x48),
    Exact(0x89),
    Exact(0x44),
    Exact(0x24),
    Exact(0x30),
    Exact(0x83),
    Exact(0xB9),
    Exact(0xB8),
    Exact(0x00),
    Exact(0x00),
    Exact(0x00),
    Exact(0x00),
    Exact(0x48),
    Exact(0x8B),
    Exact(0xD9),
    Exact(0x75),
    Exact(0x49),
    Exact(0xF6),
    Exact(0x81),
    Exact(0x1C),
    Exact(0x02),
    Exact(0x00),
    Exact(0x00),
    Exact(0x20),
];

const COMP_VISUAL_PROMOTION_AOB: &[AobToken] = &[
    Exact(0x48),
    Exact(0x89),
    Exact(0x5C),
    Exact(0x24),
    Exact(0x10),
    Exact(0x48),
    Exact(0x89),
    Exact(0x74),
    Exact(0x24),
    Exact(0x18),
    Exact(0x57),
    Exact(0x48),
    Exact(0x83),
    Exact(0xEC),
    Exact(0x20),
    Exact(0x48),
    Exact(0x8B),
    Exact(0x41),
    Exact(0x58),
    Exact(0x41),
    Exact(0x8B),
    Exact(0xF0),
    Exact(0x48),
    Exact(0x8B),
    Exact(0xFA),
    Exact(0x48),
    Exact(0x8B),
    Exact(0xD9),
];

const SIGNATURES: &[HookSignature] = &[
    HookSignature {
        target: HookTarget::Present,
        locator: SignatureLocator::Aob {
            tokens: PRESENT_AOB,
        },
    },
    HookSignature {
        target: HookTarget::IsCandidateDirectFlipCompatible,
        locator: SignatureLocator::Aob {
            tokens: OVERLAY_DIRECT_FLIP_AOB,
        },
    },
    HookSignature {
        target: HookTarget::WindowContextIsCandidateDirectFlipCompatible,
        locator: SignatureLocator::Aob {
            tokens: WINDOW_CONTEXT_DIRECT_FLIP_AOB,
        },
    },
    HookSignature {
        target: HookTarget::CompSwapChainIsCandidateDirectFlipCompatible,
        locator: SignatureLocator::Aob {
            tokens: COMP_SWAP_CHAIN_DIRECT_FLIP_AOB,
        },
    },
    HookSignature {
        target: HookTarget::CompVisualIsCandidateForPromotion,
        locator: SignatureLocator::Aob {
            tokens: COMP_VISUAL_PROMOTION_AOB,
        },
    },
    HookSignature {
        target: HookTarget::CompSwapChainIsCandidateIndependentFlipCompatible,
        locator: SignatureLocator::Aob {
            tokens: COMP_SWAP_CHAIN_INDEPENDENT_FLIP_AOB,
        },
    },
    HookSignature {
        target: HookTarget::OverlayTestMode,
        locator: SignatureLocator::RipRelativeGlobalAob {
            tokens: OVERLAY_TEST_MODE_ANCHOR_AOB,
            displacement_offset: 2,
            instruction_size: 7,
        },
    },
];

pub(super) fn build() -> HookProfile {
    HookProfile {
        signatures: SIGNATURES,
        hypotheses: ProfileHypotheses {
            swap_chain: SwapChainPathHypothesis {
                container_vtable_index: 24,
                resource_vtable_index: 19,
            },
            clip_box: ClipBoxPathHypothesis {
                context_state_pointer_offset: 0,
                offset: 0x4D0,
            },
            hardware_protected: HardwareProtectedPathHypothesis { offset: 0x4c },
            monitor_identity: MonitorIdentityPathHypothesis {
                adapter_luid_low_offset: 0x34,
                adapter_luid_high_offset: 0x38,
                target_id_offset: 0x3c,
            },
        },
    }
}
